### ISSUE TITLE
안녕하세요 질문좀 드려도될까요?

### ISSUE THREAD

**Issue by kkkapuq** [DarkTornado/KakaoTalkBot-Examples#3]
json으로 responsebody가 넘어오는 api를 사용하고싶습니다.
그런데 만들어주신 api로 json데이터를 파싱해오는 예제가 없어서요..
혹시 json파싱은 어떻게 하는지 여쭤봐도될까용

**Comment by DarkTornado** [comment]
이미 이 레포지토리에 해당 예제가 포함되어 있습니다.
https://github.com/DarkTornado/KakaoTalkBot-Examples/blob/master/%EA%B5%AC%EA%B8%80%20%EB%B2%88%EC%97%AD.js
