### ISSUE TITLE
올려주시는 글,자료 잘보고있읍니다...

### ISSUE THREAD

**Issue by oljindudol** [DarkTornado/KakaoTalkBot-Examples#4]
존경하는 개발자님
업로드해주시는 자료 코드 활용해서 길드내(-메-)
툴 만들고 업데이트중입니다.

다름이 아니라 소스관리,디버깅을 좀편하게 하는법 있을까 하고 질문남깁니다.
자바스크립트를 외부 클라우드에 업로드해서
봇소스에 import형식으로 고친함수,새로운함수 들을 불러오려 했었으나
실패하였읍니다 ㅠㅠ
매번 조그만 핸드폰 자판,디스플레이 에서 
소스고치려니 불편하고 생산성이안나오네요 좋은방법있으면 알려주세요!

감사합니다

**Comment by DarkTornado** [comment]
eval 함수를 간접적으로 호출하면 전역에서 실행된다는 점을 이용하여, 웹에 파일을 올려두고 그 파일을 읽어서 eval의 인자로 넘기는 방식으로 사용했던 적은 있어요.
자기 자신을 리로드하는 명령어도 넣어두고, 수정한 소스를 서버 등에 업로드한 뒤에 봇 계정에게 리로드를 실행하도록 채팅을 보내는 방식으로 원격 수정 비슷하게 사용했었어요.

**Comment by oljindudol** [comment]
고마워요 닼맨

**Comment by jisungbin** [comment]
close 가능해 보입니다.
